name: 'Backlog Notifier'
description: 'Automatically comments on tickets connected to your PRs when they get released and included the version.'
inputs:
  reference-repo-prefixes:
    description: 'Prefixes for issue numbers of reference repos. You can specify multiple comma-separated ones. The should be single words like BACKLOG or BUGLOG which could identify repos for backlog and bug tickets respectively. A complete identifier, as the action searches it in the PR description, should consist of this prefix and the issue number separated by a dash, e.g. `BACKLOG-539`.'
    required: true
    default: 'BACKLOG'
  reference-repo-names:
    description: 'Repository names that contain tickets to notify. This list must have the same number of elements as the repository prefixes list. Specify one repository name for each prefix. The repository must be located under the same GitHub account as the repository you use this action on.'
    required: true
    default: 'backlog'
  message:
    description: 'The message that is posted in the backlog ticket. Use `#` as placeholder for the version number.'
    required: true
    default: 'This feature has just been released for iOS 🎉 Now it takes typically 2-3 days until the release is available in the App Store.'
branding:
  icon: 'bell'  
  color: 'green'
runs:
  using: 'node12'
  main: 'index.js'